### ISSUE TITLE
Upgrade babel and ember

### ISSUE THREAD

**Issue by derekwsgray** [davidpett/ember-cli-sass-variables#5]
The version of ember-cli-babel 5.x is deprecated. Didn't want to see the warning so I'll submit a PR to upgrade.

**Comment by mjcbsn22** [comment]
https://github.com/davidpett/ember-cli-sass-variables/pull/4

**Comment by derekwsgray** [comment]
Oh, haha! Silly me, I didn't see that.

**Comment by derekwsgray** [comment]
Issue #4 should suffice.
